#!/usr/bin/env pwsh
# Runs after the example on every path (including a failed pre.ps1 or init) and removes
# the .env file pre.ps1 generated, so no generated credential configuration is left behind.

Set-StrictMode -Version 3.0
$ErrorActionPreference = 'Stop'

$envFile = Join-Path $PSScriptRoot '.env'
if ((Test-Path -LiteralPath $envFile -PathType Leaf) -and ((Get-Content -LiteralPath $envFile -TotalCount 1) -like '# Generated by pre.ps1*')) {
    Remove-Item -LiteralPath $envFile -Force
}
