#!/usr/bin/env pwsh
# avm test e2e and avm pr-check run this hook in an isolated pwsh process before
# Terraform. It maps the Azure credentials the AVM runner provides (ARM_*) onto the
# Microsoft Fabric provider's own FABRIC_* variables, because the Fabric provider does not
# read ARM_*. Hooks cannot export variables to the runner, so the values reach Terraform
# through the .env file next to this script (AVM contribution flow, "Lifecycle hooks").
#
# No secret is written: OIDC and managed identity need only IDs. FABRIC_* variables that
# are already set are inherited by Terraform unchanged and are never overwritten. With no
# ARM_* service-principal identity present (a local Azure CLI sign-in), nothing is mapped
# and the Fabric provider uses its default Azure CLI authentication.

Set-StrictMode -Version 3.0
$ErrorActionPreference = 'Stop'

$envFile = Join-Path $PSScriptRoot '.env'
$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('# Generated by pre.ps1 and removed by post.ps1. Do not commit.')

$alreadyConfigured = -not [string]::IsNullOrWhiteSpace($env:FABRIC_CLIENT_ID)
if (-not $alreadyConfigured -and -not [string]::IsNullOrWhiteSpace($env:ARM_CLIENT_ID)) {
    if ($env:ARM_USE_OIDC -eq 'true') {
        $lines.Add('FABRIC_USE_OIDC=true')
    }
    elseif ($env:ARM_USE_MSI -eq 'true') {
        $lines.Add('FABRIC_USE_MSI=true')
    }
    else {
        Write-Warning 'ARM_CLIENT_ID is set without ARM_USE_OIDC or ARM_USE_MSI. Set FABRIC_CLIENT_ID and the matching FABRIC_* credential variables yourself; no secret is mapped by this hook.'
    }

    if ($lines.Count -gt 1) {
        $lines.Add("FABRIC_CLIENT_ID=$($env:ARM_CLIENT_ID)")
        if (-not [string]::IsNullOrWhiteSpace($env:ARM_TENANT_ID)) {
            $lines.Add("FABRIC_TENANT_ID=$($env:ARM_TENANT_ID)")
        }
    }
}

Set-Content -LiteralPath $envFile -Value $lines -Encoding utf8NoBOM
